spring:
  application:
    name: system-pulse
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      skip:
        in-tests: false
      file: docker/docker-compose.db.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/system-pulse-db
    username: user
    password: postgresdbpassword
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    vhost: /
    exchange: my-exchange
    routing-key: my-routing-key
